version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  kubernetes: circleci/kubernetes@1.3.0

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: KubeDeployDemo
      # - kube-deploy:
      #     context: KubeDeployDemo

jobs:
  build:
    environment:
      IMAGE_NAME: sanghung/deploy-demo
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push sanghung/deploy-demo:latest
  
  # kube-deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - kubernetes/install
  #     - kubernetes/create-or-update-resource:
  #         get-rollout-status: true
  #         resource-file-path: deployment.yml
  #         resource-name: sanghung/deploy-demo:latest
  #         show-kubectl-command: true
  #     - kubernetes/create-or-update-resource:
  #         get-rollout-status: true
  #         resource-file-path: service.yml
  #         resource-name: sanghung/deploy-demo:latest
  #         show-kubectl-command: true