version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  kubernetes: circleci/kubernetes@1.3.0

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: KubeDeployDemo
          filters:
            branches:
              only: master

jobs:
  build:
    environment:
      IMAGE_NAME: sangh/react-kube-deploy-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest